version: "3.3"
services:
  no-tmux:
    image: bats/bats:latest
    environment:
      BASE_DIR: /code
    volumes:
      - "$PWD:/code/"
    command: /code/tests/no-tmux.bats
  tmux:
    image: andrewjstryker/tmux-ci-testing:1.0.0
    build:
      context: .
      dockerfile: tests/tmux-ci-testing.dockerfile
    environment:
      PLUGIN_HOME: /home/airline/.tmux/plugins/tmux-airline
    volumes:
      - "$PWD:/home/airline/.tmux/plugins/tmux-airline"
    command: bats "/home/airline/.tmux/plugins/tmux-airline/tests"
