#!/usr/bin/env bash
#| summary: Available native widgets alongside session and date
airline_layout_configure () {
  "$1" segment left-out '#S'
  "$1" widget left-in prefix
  "$1" widget-optional right-in online
  "$1" widget-optional right-mid cpu
  "$1" widget-optional right-out battery
  "$1" segment right-out ' '
  "$1" segment right-out '%Y-%m-%d %H:%M'
}
