#!/usr/bin/env bash
host=''; timeout_s=1
while (( $# )); do
  case "$1" in
    --host) [[ $# -ge 2 ]] || exit 2; host="$2"; shift 2 ;;
    --timeout) [[ $# -ge 2 ]] || exit 2; timeout_s="$2"; shift 2 ;;
    *) exit 2 ;;
  esac
done
ping -n -c 1 -W "$timeout_s" "$host" >/dev/null 2>&1
case "$?" in 0) printf '1\n' ;; 1) printf '0\n' ;; *) exit $? ;; esac
